import = ["~/.config/alacritty/themes/dracula.toml"]
working_directory = "/Users/jan.vicha/Projects/work/skippay/core/"
live_config_reload = false

# [shell]
# program = "/bin/zsh"
# args = ["--login"]

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 0.97
blur = false

# option_as_alt = "Both"

[window.padding]
x = 10
y = 10

[font]
normal.family = "AnonymicePro Nerd Font Mono"
normal.style = "Regular"
size = 13


[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" }, # Skip word right
  { key = "Left",  mods = "Alt", chars = "\u001BB" }, # Skip word left
  { key = "Right",  mods = "Command", chars = "\u001bOF", mode = "AppCursor"}, # End
  { key = "Left",  mods = "Command", chars = "\u001bOH", mode = "AppCursor"}, # Home
  { key = "Back",  mods = "Command", chars = "\u0015"},  # Delete line
  { key = "K",  mods = "Control", action = "ClearLogNotice"},  # Clear terminal
]
